services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: party_user
      POSTGRES_PASSWORD: party_password
      POSTGRES_DB: party_db
  web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://party_user:party_password@db:5432/party_db
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:

